// JavaScript source code
const edgeList = [{ name: "Alertness", description: '', requirement: '' }, { name: "Ambidextrious", description: '', requirement: '' },
{ name: "Arcane Background", description: '', requirement: '' },
{ name: "Arcane resistance", description: '', requirement: '' }, { name: "Improved arcane resistance", description: '', requirement: '' },
{ name: "Aristocrate", description: '', requirement: '' }, { name: "Attractive", description: '', requirement: '' },
{ name: "Very attractive", description: '', requirement: '' }, { name: "Berserk", description: '', requirement: '' },
{ name: "Brave", description: '', requirement: '' }, { name: "Brawny", description: '', requirement: '' },
{ name: "Brute", description: '', requirement: '' }, { name: "Charismatic", description: '', requirement: '' },
{ name: "Elan", description: '', cost: '', requirement: '' }, { name: "Fame", description: '', cost: '', requirement: '' },
{ name: "Famous", description: '', cost: '', requirement: '' }, { name: "Fast healer", description: '', cost: '', requirement: '' },
{ name: "Fleet-footed", description: '', cost: '', requirement: '' }, { name: "Linguist", description: '', cost: '', requirement: '' },
{ name: "Luck", description: '', cost: '', requirement: '' }, { name: "Great luck", description: '', cost: '', requirement: '' },
{ name: "Quick", description: '', cost: '', requirement: '' }, { name: "Rich", description: '', cost: '', requirement: '' },
{ name: "Filthy rich", description: '', cost: '', requirement: '' }, { name: "Block", description: '', cost: '', requirement: '' },
{ name: "Improved block", description: '', cost: '', requirement: '' }, { name: "Brawler", description: '', cost: '', requirement: '' },
{ name: "Bruiser", description: '', cost: '', requirement: '' }, { name: "Calculating", description: '', cost: '', requirement: '' },
{ name: "Combat reflexes", description: '', cost: '', requirement: '' }, { name: "Counterattack", description: '', cost: '', requirement: '' },
{ name: "Improved counterattack", description: '', cost: '', requirement: '' }, { name: "Dead shot", description: '', cost: '', requirement: '' },
{ name: "Dodge", description: '', cost: '', requirement: '' }, { name: "Improved dodge", description: '', cost: '', requirement: '' },
{ name: "Double tap", description: '', cost: '', requirement: '' }, { name: "Extraction", description: '', cost: '', requirement: '' },
{ name: "Improved extraction", description: '', cost: '', requirement: '' }, { name: "Feint", description: '', cost: '', requirement: '' },
{ name: "First strike", description: '', cost: '', requirement: '' }, { name: "Improved first strike", description: '', cost: '', requirement: '' },
{ name: "Free runner", description: '', cost: '', requirement: '' }, { name: "Frenzy", description: '', cost: '', requirement: '' },
{ name: "improved Frenzy", description: '', cost: '', requirement: '' }, { name: "Giant Killer", description: '', cost: '', requirement: '' },
{ name: "Hard to kill", description: '', cost: '', requirement: '' }, { name: "Harder to kill", description: '', cost: '', requirement: '' },
{ name: "Improvisational fighter", description: '', cost: '', requirement: '' }, { name: "Iron jaw", description: '', cost: '', requirement: '' },
{ name: "Killer instinct", description: '', cost: '', requirement: '' }, { name: "Level headed", description: '', cost: '', requirement: '' },
{ name: "Improved level headed", description: '', cost: '', requirement: '' }, { name: "Marksman", description: '', cost: '', requirement: '' },
{ name: "Martial artist", description: '', cost: '', requirement: '' }, { name: "Martial warrior", description: '', cost: '', requirement: '' },
{ name: "Mighty blow", description: '', cost: '', requirement: '' }, { name: "Nerves of steel", description: '', cost: '', requirement: '' },
{ name: "Improved nerves of steel", description: '', cost: '', requirement: '' }, { name: "No mercy", description: '', cost: '', requirement: '' },
{ name: "Rapid fire", description: '', cost: '', requirement: '' }, { name: "Improved rapid fire", description: '', cost: '', requirement: '' },
{ name: "Rock and roll", description: '', cost: '', requirement: '' }, { name: "Steady hands", description: '', cost: '', requirement: '' },
{ name: "Sweep", description: '', cost: '', requirement: '' }, { name: "Improved sweep", description: '', cost: '', requirement: '' },
{ name: "Trademark weapon", description: '', cost: '', requirement: '' }, { name: "Improved trademark weapon", description: '', cost: '', requirement: '' },
{ name: "Two-fisted", description: '', cost: '', requirement: '' }, { name: "Two-gun kid", description: '', cost: '', requirement: '' },
{ name: "Command", description: '', cost: '', requirement: '' }, { name: "Command presence", description: '', cost: '', requirement: '' },
{ name: "Fervor", description: '', cost: '', requirement: '' }, { name: "Hold the line", description: '', cost: '', requirement: '' },
{ name: "Inspire", description: '', cost: '', requirement: '' }, { name: "Natural leader", description: '', cost: '', requirement: '' },
{ name: "Tactitian", description: '', cost: '', requirement: '' }, { name: "Master tactitian", description: '', cost: '', requirement: '' },
{ name: "Artificer", description: '', cost: '', requirement: '' }, { name: "Channeling", description: '', cost: '', requirement: '' },
{ name: "Concentration", description: '', cost: '', requirement: '' }, { name: "Extra Effort", description: '', cost: '', requirement: '' },
{ name: "Gadgeteer", description: '', cost: '', requirement: '' }, { name: "Holy/unholy warrior", description: '', cost: '', requirement: '' },
{ name: "Mentalist", description: '', cost: '', requirement: '' }, { name: "New powers", description: '', cost: '', requirement: '' },
{ name: "Power points", description: '', cost: '', requirement: '' }, { name: "Power surge", description: '', cost: '', requirement: '' },
{ name: "Rapid recharge", description: '', cost: '', requirement: '' }, { name: "Improved rapid recharge", description: '', cost: '', requirement: '' },
{ name: "Soul drain", description: '', cost: '', requirement: '' }, { name: "Wizard", description: '', cost: '', requirement: '' },
{ name: "Ace", description: '', cost: '', requirement: '' }, { name: "Acrobat", description: '', cost: '', requirement: '' },
{ name: "Combat acrobat", description: '', cost: '', requirement: '' }, { name: "Assassin", description: '', cost: '', requirement: '' },
{ name: "Investigator", description: '', cost: '', requirement: '' }, { name: "Jack-of-all-trades", description: '', cost: '', requirement: '' },
{ name: "Mcgyver", description: '', cost: '', requirement: '' }, { name: "Mr.Fix it", description: '', cost: '', requirement: '' },
{ name: "Scholar", description: '', cost: '', requirement: '' }, { name: "Soldier", description: '', cost: '', requirement: '' },
{ name: "Thief", description: '', cost: '', requirement: '' }, { name: "Woodsman", description: '', cost: '', requirement: '' },
{ name: "Bolster", description: '', cost: '', requirement: '' }, { name: "Common bond", description: '', cost: '', requirement: '' },
{ name: "Connections", description: '', cost: '', requirement: '' }, { name: "Humiliate", description: '', cost: '', requirement: '' },
{ name: "Menacing", description: '', cost: '', requirement: '' }, { name: "Provoke", description: '', cost: '', requirement: '' },
{ name: "Rabble-rouser", description: '', cost: '', requirement: '' }, { name: "Reliable", description: '', cost: '', requirement: '' },
{ name: "Retort", description: '', cost: '', requirement: '' }, { name: "Streetwise", description: '', cost: '', requirement: '' },
{ name: "String willed", description: '', cost: '', requirement: '' }, { name: "Iron will", description: '', cost: '', requirement: '' },
{ name: "Work the room", description: '', cost: '', requirement: '' }, { name: "work the crowd", description: '', cost: '', requirement: '' },
{ name: "Beast bond", description: '', cost: '', requirement: '' }, { name: "Beast master", description: '', cost: '', requirement: '' },
{ name: "Champion", description: '', requirement: '' }, { name: "Chi", description: '', requirement: '' },
{ name: "Danger sense", description: '', requirement: '' }, { name: "Healer", description: '', requirement: '' },
{ name: "Liquid courage", description: '', requirement: '' }, { name: "Scavenger", description: '', requirement: '' },
{ name: "Followers", description: '', requirement: '' }, { name: "Professional", description: '', requirement: '' },
{ name: "Expert", description: '', requirement: '' }, { name: "Master", description: '', requirement: '' },
{ name: "Sidekick", description: '', requirement: '' }, { name: "Tough as nails", description: '', requirement: '' },
{ name: "Tougher than nails", description: '', requirement: '' }, { name: "Weapon master", description: '', requirement: '' },
{ name: "Master of arms", description: '', requirement: '' }, { name: "Flame blast", description: '', requirement: '' },
{ name: "Improved fiery aura", description: '', requirement: '' }, { name: "Improved fire mastery", description: '', requirement: '' },
{ name: "Improved flame bolt", description: '', requirement: '' }, { name: "Rapid flame bolt", description: '', requirement: '' },
{ name: "Read the flame", description: '', requirement: '' }, { name: "Beyond the limit", description: '', requirement: '' },
{ name: "Upgrade", description: '', requirement: '' }, { name: "Gun nut", description: '', requirement: '' },
{ name: "Gymnastic mastery", description: '', requirement: '' }, { name: "Off the handle", description: '', requirement: '' },
{ name: "Split the seconds", description: '', requirement: '' }, { name: "Sublime chaos", description: '', requirement: '' },
{ name: "Cyberkinetic awareness", description: '', requirement: '' }, { name: "Improved cyberkinetic awareness", description: '', requirement: '' },
{ name: "cyberkinetic denial", description: '', requirement: '' }, { name: "Improved cyber-armor", description: '', requirement: '' },
{ name: "Master cyber-armor", description: '', requirement: '' }, { name: "Improved psi-sword", description: '', requirement: '' },
{ name: "Master psi-sword", description: '', requirement: '' }, { name: "Psi-shield", description: '', requirement: '' },
{ name: "Dragon fast regeneration", description: '', requirement: '' }, { name: "Dragon flaming scales", description: '', requirement: '' },
{ name: "Dragon low light vision", description: '', requirement: '' }, { name: "Dragon metamorphosis", description: '', requirement: '' },
{ name: "Dragon grows larger", description: '', requirement: '' }, { name: "Dragon grows huge", description: '', requirement: '' },
{ name: "Dragon teleportation", description: '', requirement: '' }, { name: "Burn brighter", description: '', requirement: '' },
{ name: "Burn for glory", description: '', requirement: '' }, { name: "Burn faster", description: '', requirement: '' },
{ name: "Burn past the pain", description: '', requirement: '' }, { name: "Burn for tomorrow", description: '', requirement: '' },
{ name: "Freshly juiced", description: '', requirement: '' }, { name: "Ley line observation sphere", description: '', requirement: '' },
{ name: "Ley line phasing", description: '', requirement: '' }, { name: "Ley line gate", description: '', requirement: '' },
{ name: "Upgradeable", description: '', requirement: '' }, { name: "Charge", description: '', requirement: '' },
{ name: "Overrun", description: '', requirement: '' }, { name: "Dirty fighter", description: '', requirement: '' },
{ name: "Tricky fighter", description: '', requirement: '' }, { name: "Blaster", description: '', requirement: '' },
{ name: "Expert blaster", description: '', requirement: '' }, { name: "Master blaster", description: '', requirement: '' },
{ name: "Cyber-psychic alignment", description: '', requirement: '' }, { name: "Improved cyber-psychic alignment", description: '', requirement: '' },
{ name: "Major psionic", description: '', requirement: '' }, { name: "Master psionic", description: '', requirement: '' },
{ name: "Master of magic", description: '', requirement: '' }, { name: "Possession", description: '', requirement: '' },
{ name: "Psi-blade", description: '', requirement: '' }, { name: "Exceptional rapid recharge", description: '', requirement: '' },
{ name: "Sixth sense", description: '', requirement: '' }, { name: "Telemechanics", description: '', requirement: '' },
{ name: "Combat ace", description: '', requirement: '' }, { name: "Power armor jock", description: '', requirement: '' },
{ name: "Robot vechicle jock", description: '', requirement: '' }, { name: "I know a guy", description: '', requirement: '' },
{ name: "Scrounger", description: '', requirement: '' }, { name: "Quick draw", description: '', requirement: '' },
{ name: "Fast draw", description: '', requirement: '' }, { name: "Bio-manipulation", description: '', requirement: '' },
{ name: "Dragon celerity", description: '', requirement: '' }, { name: "Dragon frost scales", description: '', requirement: '' },
{ name: "Dragon master psychic", description: '', requirement: '' }, { name: "Dragon sharp horns", description: '', requirement: '' },
{ name: "Master elementalist", description: '', requirement: '' }, { name: "Diabolist", description: '', requirement: '' },
{ name: "Elementalist", description: '', requirement: '' }, { name: "Born to ride", description: '', requirement: '' },
{ name: "Live to ride", description: '', requirement: '' }, { name: "Familiar link", description: '', requirement: '' },
{ name: "Supernatural strength", description: '', requirement: '' }, { name: "Delphi juicer treatment", description: '', requirement: '' },
{ name: "Genius", description: '', requirement: '' }, { name: "Hyperion treatment", description: '', requirement: '' },
{ name: "Mega-juicer treatment", description: '', requirement: '' }, { name: "Phaeton treatment", description: '', requirement: '' },
{ name: "Synthetic immortality", description: '', requirement: '' }, { name: "Titan treatment", description: '', requirement: '' },
{ name: "Sharpshooting", description: '', requirement: '' }, { name: "Trick shooting", description: '', requirement: '' },
{ name: "Take em down", description: '', requirement: '' }, { name: "Improved take em down", description: '', requirement: '' },
{ name: "Combat lifesaver", description: '', requirement: '' }, { name: "Improved combat lifesaver", description: '', requirement: '' },
{ name: "conditioned", description: '', requirement: '' }, { name: "Demolitionist", description: '', requirement: '' },
{ name: "Expert demolitionist", description: '', requirement: '' }, { name: "Field intel", description: '', requirement: '' },
{ name: "Legacy scout", description: '', requirement: '' }, { name: "Justice ranger", description: '', requirement: '' },
{ name: "Monster slayer", description: '', requirement: '' }, { name: "Magi of Dweomer", description: '', requirement: '' },
{ name: "Psychic of psyscape", description: '', requirement: '' }, { name: "Psychic of psyscape", description: '', requirement: '' },
{ name: "Arcane marksman", description: '', requirement: '' }, { name: "Elemental attunement", description: '', requirement: '' },
{ name: "Life sign harmony", description: '', requirement: '' }, { name: "Warlock", description: '', requirement: '' },
{ name: "Dream vision", description: '', requirement: '' }, { name: "Minor item creation", description: '', requirement: '' },
{ name: "Major item creation", description: '', requirement: '' }, { name: "Psi-weapon manipultaion", description: '', requirement: '' },
{ name: "Adept", description: '', requirement: '' }, { name: "Conjurer", description: '', requirement: '' },
{ name: "Controller", description: '', requirement: '' }, { name: "Grey seer", description: '', requirement: '' },
{ name: "Totem warrior", description: '', requirement: '' }, { name: "One with magic", description: '', requirement: '' },
{ name: "Dimensional portal", description: '', requirement: '' }, { name: "Gardener of the white rose", description: '', requirement: '' },
{ name: "Gateway knight", description: '', requirement: '' }, { name: "Master necromancer", description: '', requirement: '' },
{ name: "Pounce", description: '', requirement: '' }, { name: "Shift the arcane", description: '', requirement: '' },
{ name: "Teleportation hitchhiker", description: '', requirement: '' }, { name: "Thrall", description: '', requirement: '' },
{ name: "Slow kill bite", description: '', requirement: '' }, { name: "Beast rider", description: '', requirement: '' },
{ name: "Frontiersman", description: '', requirement: '' }, { name: "Pathfinder", description: '', requirement: '' },
{ name: "Squire of the white rose", description: '', requirement: '' }, { name: "Reids ranger", description: '', requirement: '' },
{ name: "Tundra ranger", description: '', requirement: '' }, { name: "Vampire killer", description: '', requirement: '' },
{ name: "Elite vampire Killer", description: '', requirement: '' }];