// JavaScript source code
const hindrancesList = [{ name: 'All Thumbs', description: '', cost: '' }, { name: 'Anemic', description: '', cost: '' },
{ name: 'Arrogant', description: '', cost: '' }, { name: 'Bad eyes', description: '', cost: '' },
{ name: 'Bad luck', description: '', cost: '' }, { name: 'Big mouth', description: '', cost: '' },
{ name: 'Blind', description: '', cost: '' }, { name: 'Bloodthirsty', description: '', cost: '' },
{ name: 'Cant swim', description: '', cost: '' }, { name: 'Cautious', description: '', cost: '' },
{ name: 'Clueless', description: '', cost: '' }, { name: 'Clumsy', description: '', cost: '' },
{ name: 'Code of honor', description: '', cost: '' }, { name: 'Curious', description: '', cost: '' },
{ name: 'Death wish', description: '', cost: '' }, { name: 'Delusional', description: '', cost: '' },
{ name: 'Doubting Thomas', description: '', cost: '' }, { name: 'Driven', description: '', cost: '' },
{ name: 'Elderly', description: '', cost: '' }, { name: 'Enemy', description: '', cost: '' },
{ name: 'Greedy', description: '', cost: '' }, { name: 'Habit', description: '', cost: '' },
{ name: 'Hard of hearing', description: '', cost: '' }, { name: 'Heroic', description: '', cost: '' },
{ name: 'Hesitant', description: '', cost: '' }, { name: 'Illiterate', description: '', cost: '' },
{ name: 'Impulsive', description: '', cost: '' }, { name: 'Jealous', description: '', cost: '' },
{ name: 'Loyal', description: '', cost: '' }, { name: 'Mean', description: '', cost: '' },
{ name: 'Mild mannered', description: '', cost: '' }, { name: 'Mute', description: '', cost: '' },
{ name: 'Obese', description: '', cost: '' }, { name: 'Obligation', description: '', cost: '' },
{ name: 'One arm', description: '', cost: '' }, { name: 'One eye', description: '', cost: '' },
{ name: 'Outsider', description: '', cost: '' }, { name: 'Overconfident', description: '', cost: '' },
{ name: 'Pacifist', description: '', cost: '' }, { name: 'Phobia', description: '', cost: '' },
{ name: 'Poverty', description: '', cost: '' }, { name: 'Quick', description: '', cost: '' },
{ name: 'Ruthless', description: '', cost: '' }, { name: 'Secret', description: '', cost: '' },
{ name: 'Shamed', description: '', cost: '' }, { name: 'Slow', description: '', cost: '' },
{ name: 'Small', description: '', cost: '' }, { name: 'Stubborn', description: '', cost: '' },
{ name: 'Suspicious', description: '', cost: '' }, { name: 'Thin skinned', description: '', cost: '' },
{ name: 'Tongue-tied', description: '', cost: '' }, { name: 'Ugly', description: '', cost: '' },
{ name: 'Vengeful', description: '', cost: '' }, { name: 'Vow', description: '', cost: '' },
{ name: 'Wanted', description: '', cost: '' }, { name: 'Yellow', description: '', cost: '' },
{ name: 'Young', description: '', cost: '' }, { name: 'Mania', description: '', cost: '' },
{ name: 'Arcane averse', description: '', cost: '' }, { name: 'Coalition', description: '', cost: '' },
{ name: 'Partisan', description: '', cost: '' }, { name: 'Post-traumatic stress disorder', description: '', cost: '' }];